---

- name: INCLUDE | Install packages
  import_tasks: install.yml
  when: ansible_os_family == 'Debian'

- name: INCLUDE | Install Nginx
  import_tasks: nginx.yml
  when: ansible_os_family == 'Debian'



